#!/usr/bin/env bash

# Usage:
#  bld [release]

DEFAULT_RELEASE="2.6.5"
RELEASE=${1:-$DEFAULT_RELEASE}
DEST=$PWD/cooked/tiddlywiki.com
mkdir -p cooked
mkdir -p cooked/tiddlywiki.com
cook $PWD/index.html.recipe -d $DEST -o index.$RELEASE.html
cook $PWD/empty.html.recipe -d $DEST -o empty.$RELEASE.html
cp ../tiddlywiki/java/TiddlySaver.jar $DEST/TiddlySaver.jar
rm $DEST/empty.$RELEASE.zip
cp $DEST/empty.$RELEASE.html tmp/empty.html
zip -j $DEST/empty.$RELEASE.zip tmp/empty.html $DEST/TiddlySaver.jar
rm tmp/empty.html
