//@ts-check
import { defineConfig } from "eslint/config";
import globals from "globals";
import js from "@eslint/js";
import eslint from "eslint";
import stylistic from "@stylistic/eslint-plugin";
import esx from "eslint-plugin-es-x";

/** @type {import("eslint").Linter.Config} */
const es2017rules = {
    //@ts-ignore
    plugins: esx.configs["flat/restrict-to-es2017"].plugins,
    //@ts-ignore
    rules: esx.configs["flat/restrict-to-es2017"].rules,
    ignores: ["bin/**/*", "core-server/**/*"],
};
/** @type {import("eslint").Linter.Config} */
const es2023rules = {
    //@ts-ignore
    plugins: esx.configs["flat/restrict-to-es2023"].plugins,
    //@ts-ignore
    rules: esx.configs["flat/restrict-to-es2023"].rules,
    files: ["bin/**/*", "core-server/**/*"],
};



export default defineConfig([{
    ignores: [
        // Ignore "third party" code whose style we will not change.
        "boot/sjcl.js",
        "core/modules/utils/base64-utf8/base64-utf8.module.js",
        "core/modules/utils/base64-utf8/base64-utf8.module.min.js",
        "core/modules/utils/diff-match-patch/diff_match_patch.js",
        "core/modules/utils/diff-match-patch/diff_match_patch_uncompressed.js",
        "core/modules/utils/dom/csscolorparser.js",
        "plugins/tiddlywiki/*/files/",
        "eslint.config.mjs",
        "playwright.config.js",
        "**/output/**"
    ],

},
js.configs.recommended,
{
    languageOptions: {
        ecmaVersion: "latest",
        sourceType: "commonjs",
    },

    plugins: {
        "@stylistic": stylistic
    },

    rules: {
        "@stylistic/array-bracket-newline": "off",
        "@stylistic/array-bracket-spacing": "off",
        "array-callback-return": "off",
        "@stylistic/array-element-newline": "off",
        "arrow-body-style": "error",
        "@stylistic/arrow-parens": ["error", "as-needed"],
        "@stylistic/arrow-spacing": ["error", {
            after: true,
            before: true,
        }],
        "block-scoped-var": "off",
        "@stylistic/block-spacing": "off",
        "@stylistic/brace-style": "off",
        "callback-return": "off",
        camelcase: "off",
        "capitalized-comments": "off",
        "class-methods-use-this": "error",
        "@stylistic/comma-dangle": "off",
        "@stylistic/comma-spacing": "off",
        "@stylistic/comma-style": "off",
        complexity: "off",
        "@stylistic/computed-property-spacing": "off",
        "consistent-return": "off",
        "consistent-this": "off",
        curly: "off",
        "default-case": "off",
        "default-case-last": "error",
        "default-param-last": "error",
        "@stylistic/dot-location": "off",
        "dot-notation": "off",
        "@stylistic/eol-last": "off",
        eqeqeq: "off",
        "@stylistic/func-call-spacing": "off",
        "func-name-matching": "off",
        "func-names": "off",
        "func-style": "off",
        "@stylistic/function-call-argument-newline": "off",
        "@stylistic/function-paren-newline": "off",
        "@stylistic/generator-star-spacing": "error",
        "global-require": "off",
        "grouped-accessor-pairs": "error",
        "guard-for-in": "off",
        "handle-callback-err": "off",
        "id-denylist": "error",
        "id-length": "off",
        "id-match": "error",
        "@stylistic/implicit-arrow-linebreak": "error",
        "@stylistic/indent": "off",
        "init-declarations": "off",
        "@stylistic/jsx-quotes": "error",
        "@stylistic/key-spacing": "off",
        "@stylistic/keyword-spacing": ["error", {
            before: true,
            after: false,
            overrides: {
                case: { after: true },
                do: { after: true },
                else: { after: true },
                return: { after: true },
                throw: { after: true },
                try: { after: true },
            },
        }],
        "@stylistic/line-comment-position": "off",
        "@stylistic/linebreak-style": "off",
        "@stylistic/lines-around-comment": "off",
        "@stylistic/lines-around-directive": "off",
        "@stylistic/lines-between-class-members": "error",
        "max-classes-per-file": "error",
        "max-depth": "off",
        "@stylistic/max-len": "off",
        "max-lines": "off",
        "max-lines-per-function": "off",
        "max-nested-callbacks": "error",
        "max-params": "off",
        "max-statements": "off",
        "@stylistic/max-statements-per-line": "off",
        "@stylistic/multiline-comment-style": "off",
        "@stylistic/multiline-ternary": "off",
        "@stylistic/new-parens": "off",
        "@stylistic/newline-after-var": "off",
        "@stylistic/newline-before-return": "off",
        "@stylistic/newline-per-chained-call": "off",
        "no-alert": "off",
        "no-array-constructor": "off",
        "no-await-in-loop": "error",
        "no-bitwise": "off",
        "no-buffer-constructor": "off",
        "no-caller": "error",
        "@stylistic/no-confusing-arrow": "error",
        "no-console": "off",
        "no-constant-condition": ["error", { checkLoops: false }],
        "no-constructor-return": "error",
        "no-continue": "off",
        "no-div-regex": "off",
        "no-duplicate-imports": "error",
        "no-else-return": "off",
        "no-empty-function": "off",
        "no-eq-null": "off",
        "no-eval": "off",
        "no-extend-native": "off",
        "no-extra-bind": "off",
        "no-extra-label": "off",
        "@stylistic/no-extra-parens": "off",
        "@stylistic/no-floating-decimal": "off",
        "no-implicit-coercion": ["error", {
            boolean: false,
            number: false,
            string: false,
        }],
        "no-implicit-globals": "off",
        "no-implied-eval": "error",
        "no-inline-comments": "off",
        "no-invalid-this": "off",
        "no-iterator": "error",
        "no-label-var": "off",
        "no-labels": "off",
        "no-lone-blocks": "off",
        "no-lonely-if": "off",
        "no-loop-func": "off",
        "no-loss-of-precision": "error",
        "no-magic-numbers": "off",
        "@stylistic/no-mixed-operators": "off",
        "no-mixed-requires": "off",
        "no-multi-assign": "off",
        "@stylistic/no-multi-spaces": "off",
        "no-multi-str": "error",
        "@stylistic/no-multiple-empty-lines": "off",
        "@stylistic/no-native-reassign": "off",
        "no-negated-condition": "off",
        "no-unsafe-negation": "error",
        "no-nested-ternary": "off",
        "no-new": "off",
        "no-new-func": "off",
        "no-object-constructor": "off",
        "no-new-require": "error",
        "no-new-wrappers": "error",
        "no-octal-escape": "error",
        "no-param-reassign": "off",
        "no-path-concat": "error",
        "no-plusplus": "off",
        "no-process-env": "off",
        "no-process-exit": "off",
        "no-promise-executor-return": "error",
        "no-proto": "off",
        "no-restricted-exports": "error",
        "no-restricted-globals": ["error", "self"],
        "no-restricted-imports": "error",
        "no-restricted-modules": "error",
        "no-restricted-properties": "error",
        "no-restricted-syntax": "error",
        "no-return-assign": "off",
        "no-script-url": "off",
        "no-self-compare": "off",
        "no-sequences": "off",
        "no-shadow": "off",
        "@stylistic/no-spaced-func": "off",
        "no-sync": "off",
        "@stylistic/no-tabs": "off",
        "no-template-curly-in-string": "error",
        "no-ternary": "off",
        "no-throw-literal": "off",
        "@stylistic/no-trailing-spaces": "off",
        "no-undef-init": "off",
        "no-undefined": "off",
        "no-underscore-dangle": "off",
        "no-unmodified-loop-condition": "off",
        "no-unneeded-ternary": "off",
        "no-unreachable-loop": "error",
        "no-unused-expressions": "off",
        "no-use-before-define": "off",
        "no-useless-backreference": "error",
        "no-useless-call": "off",
        "no-useless-computed-key": "error",
        "no-useless-concat": "off",
        "no-useless-constructor": "error",
        "no-useless-rename": "error",
        "no-useless-return": "off",
        "no-var": "off",
        "no-void": "off",
        "no-warning-comments": "off",
        "@stylistic/no-whitespace-before-property": "error",
        "@stylistic/nonblock-statement-body-position": ["error", "any"],
        "@stylistic/object-curly-newline": "off",
        "@stylistic/object-curly-spacing": "off",
        "@stylistic/object-property-newline": "off",
        "object-shorthand": "off",
        "one-var": "off",
        "@stylistic/one-var-declaration-per-line": "off",
        "operator-assignment": "off",
        "@stylistic/operator-linebreak": "off",
        "@stylistic/padded-blocks": "off",
        "@stylistic/padding-line-between-statements": "error",
        "prefer-arrow-callback": "off",
        "prefer-const": "off",
        "prefer-destructuring": "off",
        "prefer-exponentiation-operator": "off",
        "prefer-named-capture-group": "off",
        "prefer-numeric-literals": "error",
        "prefer-object-spread": "off",
        "prefer-promise-reject-errors": "error",
        "prefer-regex-literals": "off",
        "prefer-rest-params": "off",
        "prefer-spread": "off",
        "prefer-template": "off",
        "@stylistic/quote-props": "off",
        "@stylistic/quotes": ["error", "double", { avoidEscape: true }],
        radix: "off",
        "require-atomic-updates": "error",
        "require-await": "error",
        "require-jsdoc": "off",
        "require-unicode-regexp": "off",
        "@stylistic/rest-spread-spacing": "error",
        "@stylistic/semi": "off",
        "@stylistic/semi-spacing": "off",
        "@stylistic/semi-style": "off",
        "sort-imports": "error",
        "sort-keys": "off",
        "sort-vars": "off",
        "@stylistic/space-before-blocks": "off",
        "@stylistic/space-before-function-paren": "off",
        "@stylistic/space-in-parens": "off",
        "@stylistic/space-infix-ops": "off",
        "@stylistic/space-unary-ops": "off",
        "@stylistic/spaced-comment": "off",
        strict: "off",
        "@stylistic/switch-colon-spacing": "off",
        "symbol-description": "error",
        "@stylistic/template-curly-spacing": "error",
        "@stylistic/template-tag-spacing": "error",
        "unicode-bom": ["error", "never"],
        "valid-jsdoc": "off",
        "valid-typeof": ["error", { requireStringLiterals: false }],
        "vars-on-top": "off",
        "@stylistic/wrap-iife": "off",
        "@stylistic/wrap-regex": "off",
        "@stylistic/yield-star-spacing": "error",
        yoda: "off",
        // temporary rules
        "no-useless-escape": "off",
        "no-unused-vars": "off",
        "no-empty": "off",
        "@stylistic/no-extra-semi": "off",
        "no-redeclare": "off",
        "no-control-regex": "off",
        "@stylistic/no-mixed-spaces-and-tabs": "off",
        "no-extra-boolean-cast": "off",
        "no-prototype-builtins": "off",
        "no-undef": "off",
        "no-unreachable": "off",
        "no-self-assign": "off",
    },

},
    es2017rules,
    es2023rules
]);
