#!/usr/bin/env bash

# Usage:
#  bldalpha [release]

# Requires a cook script on $PATH.
# See 'cook' in this directory for a sample.

DEFAULT_RELEASE=`cat ALPHA`
RELEASE=${1:-$DEFAULT_RELEASE}
RECIPE=$PWD/tiddlywiki.html.recipe
RECIPE_EXT_JS=$PWD/tiddlywiki_externaljs.html.recipe
RECIPE_EXT_JS_TS=$PWD/tiddlywiki_externaljs_tiddlyspace_alpha.html.recipe
cook $RECIPE tiddlywiki.$RELEASE.html
cook $RECIPE tiddlywiki_compressed.$RELEASE.html -cr -Cr -Dr
cook $RECIPE twcore.$RELEASE.js -j
cook $RECIPE_EXT_JS tiddlywiki_externaljs.$RELEASE.html
cook $RECIPE_EXT_JS_TS tiddlywiki_externaljs_tiddlyspace.$RELEASE.html
