name: Bug report
description: Create a report to help us improve TiddlyWiki 5
title: "[BUG] "
body:
  - type: textarea
    id: Describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: Expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: Reproduce
    attributes:
      label: To Reproduce
      description: "Steps to reproduce the behavior:"
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: Screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag image here to upload screenshot!
    validations:
      required: false
  - type: textarea
    id: Configuration
    attributes:
      label: TiddlyWiki Configuration
      description: please complete the following information
      value: |
        - Version [e.g. v5.1.24]
        - Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
        - Plugins installed [e.g. Freelinks, TiddlyMap]

        ### Desktop (please complete the following information):

        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]

        ### Smartphone (please complete the following information):

        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
    validations:
      required: true
  - type: textarea
    id: Context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
