apiVersion: v1
kind: Service
metadata:
  name: tiddlywiki
  labels:
    app.kubernetes.io/name: tiddlywiki
    app.kubernetes.io/component: wiki
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tiddlywiki
    app.kubernetes.io/component: wiki
  ports:
    - name: http
      port: 80
      targetPort: http    # resolves to named port 8080 on the container
      protocol: TCP
  sessionAffinity: None
