name: Comment on PR build size (Trusted workflow)

on:
  repository_dispatch:
    types: [pr_build_size_report]

jobs:
  comment-build-size-on-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Build and check size
      uses: TiddlyWiki/cerebrus@v3
      with:
        pr_number: ${{ github.event.client_payload.pr_number }}
        repo: ${{ github.repository }}
        base_ref: ${{ github.event.client_payload.base_branch }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        mode: size:comment
        pr_size: ${{ github.event.client_payload.pr_size }}
        base_size: ${{ github.event.client_payload.base_size }}